# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c44e6de90164c678fa82034494fea574e83a6f5839cd930cace1627aa1a0c2566834d8edd033a4b7aa76006e1535bb3040e957de5a82c522c6973bba7202d4ce

test:
  secret_key_base: fa30cd63a8c9e1f8c5310ea32e9353e3204360a7b70f7d4a2128b41c7256559fbce4e86218e0b9d05c21f07fa2ce16a72d6258aa8471acfc8a796218c1651072

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
